// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_nL3KDB2kRY5swZsBzxhyDDWB8N9-t8s',
    appId: '1:318487330749:web:ad4620d2817fb1c8249cd4',
    messagingSenderId: '318487330749',
    projectId: 'chateo-42a01',
    authDomain: 'chateo-42a01.firebaseapp.com',
    storageBucket: 'chateo-42a01.firebasestorage.app',
    measurementId: 'G-L16BGLH3TS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXDo_E_hrYBT3bqEPVnZGy5qY3x8f9Yw0',
    appId: '1:318487330749:android:bfe4031998431f11249cd4',
    messagingSenderId: '318487330749',
    projectId: 'chateo-42a01',
    storageBucket: 'chateo-42a01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXfZUrgNTEZ4p4HRrBSvha6wZ-yWhY02M',
    appId: '1:318487330749:ios:9372ed5f0a168e21249cd4',
    messagingSenderId: '318487330749',
    projectId: 'chateo-42a01',
    storageBucket: 'chateo-42a01.firebasestorage.app',
    iosBundleId: 'com.example.chateoApp',
  );

}